version: 2
jobs:
  build:
    docker:
      - image: google/cloud-sdk
        auth:
          username: _json_key  # default username when using a JSON key file to authenticate
          password: $GCLOUD_SERVICE_KEY  # JSON service account you created, do not encode to base64
    
    steps:
      - checkout

      - run:
          name: install dependencies
          command: |
            apt-get install python3-venv -y
            python3 -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt
      - run:
          name: run tests
          command: |
            . venv/bin/activate
            python test.py
      - run:
          name: Gcloud Setup
          command: |
            sudo gcloud --quiet components update
            echo $GCLOUD_SERVICE_KEY | gcloud auth activate-service-account --key-file=-
            gcloud --quiet config set project ${GOOGLE_PROJECT_ID}
            gcloud --quiet config set compute/zone ${GOOGLE_COMPUTE_ZONE}
            gcloud config set project ghana360
            gcloud app deploy app.yaml
